version: '3.8'
services:
    backend_flask_app:
        container_name: ${TEAM_NAME}_backend_app
        restart: always
        build:
                context: ./backend
                dockerfile: Dockerfile
        ports: 
                - 5000:5000
        depends_on:
                - db
        environment:
                - DB_NAME=${TEAM_NAME}_db
        networks:
                flask_network:
                        aliases:
                                - flask-network
        command: flask run --host=0.0.0.0 --port=5000
    db:
        container_name: ${TEAM_NAME}_db
        image: mysql:5.7
        restart: always
        environment:
                - MYSQL_USER=${MYSQL_ONLINE_USER}
                - MYSQL_PASSWORD=${MYSQL_ONLINE_PASSWORD}
                - MYSQL_DATABASE=${MYSQL_ONLINE_DATABASE}
                - MYSQL_ROOT_PASSWORD=${MYSQL_ONLINE_ROOT_PASSWORD}
        volumes:
                - flask_volume:/var/lib/mysql
                - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
                - flask_network
volumes:
        flask_volume:
networks:
        flask_network: